- hosts: all
  remote_user: root
  vars:
    db_name: e2 
    db_user: e2 
    db_password: hpmor1 

    email: lyamets.misha@gmail.com 
    distrib: https://blogengine.ru/download/e2_distr_v3576.zip #(beta)

    path: /var/www/aegea
    domain: "{{ inventory_hostname }}"
    http_port: 80

    # php.ini
    php_max_execution_time: '300'
    php_display_errors: 'On'
    php_display_startup_errors: 'On'
    php_html_errors: 'On'
    php_post_max_size: '128M'
    php_upload_max_filesize: '130M'
    php_memory_limit: '260M'
    php_date_timezone: 'US/Central'

    # vsftpd
    vsftpd_anonymous_enable: 'NO'
    vsftpd_local_enable: 'YES'
    vsftpd_write_enable: 'YES'
    vsftpd_local_umask: '077'

  tasks:
  - name: Packages
    apt:
      pkg:
        - unzip
        - php 
        - php-gd
        - php-mysql
        - php-mbstring
        - apache2
        - libapache2-mod-php
        - mysql-server
        - libmysqlclient-dev
        - python-mysqldb
      state: present
      update_cache: yes
    
  - name: PHP | Configuration file, php.ini
    action: template src=templates/php.ini dest=/etc/php/7.2/apache2/php.ini

  ##
  # Mysql server setup.
  #
  - name: ensure mysql is running and starts on boot
    service: name=mysql state=started enabled=true

  - name: MySQL | Create mysql user
    action: mysql_user user={{ db_user }} password={{ db_password }} priv='*.*:ALL,GRANT' host=localhost state=present
    # tags: common

  - name: Create a new database
    mysql_db:
      name: "{{ db_name }}"
      login_user: "{{ db_user }}"
      login_password: "{{ db_password }}"
      state: present

 
  ##
  # Aegea installation
  #
  - name: Creates directory
    file: 
      path: "{{ path }}"
      state: directory
      mode: 0755

  - name: copy aegea
    unarchive:
      src: "{{ distrib }}"
      dest: "{{ path }}"
      owner: www-data
      group: www-data
      creates: "{{ path }}/favicon.ico"
      # exclude: readme.txt - exclude causes this error: fatal: [aaa.jazzcloud.co]: FAILED! => {"changed": false, "dest": "/var/www/egea", "failed": true, "gid": 0, "group": "root", "handler": "ZipArchive", "mode": "0755", "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/var/www/egea/.htaccess'", "owner": "root", "size": 4096, "src": "/tmp/ansible_QRkRTJ/e2_distr_v2970.zip", "state": "directory", "uid": 0}
      remote_src: True

  - name: create aegea config
    template: src=templates/config.php dest={{ path }}/user/config.php

  # - name: download info.php
  #   copy:
  #     src: dist/info.php
  #     dest: "{{ path }}/info.php"

  - name: Set user and group
    file:
      path: /var/www
      owner: www-data
      group: www-data
      recurse: Yes


  ##
  # Apache server setup.
  #
  - name: apache2.conf
    template: src=templates/apache2.conf dest=/etc/apache2/apache2.conf
    notify:
      - restart apache2

  - name: enabled mod_rewrite
    apache2_module: name=rewrite state=present
    notify:
      - restart apache2

  - name: apache2 listen on port {{ http_port }}
    lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
    notify:
      - restart apache2

  - name: create virtual host file
    template: src=templates/virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

  - name: a2ensite {{ domain }}
    command: a2ensite {{ domain }}
    args:
      creates: /etc/apache2/sites-enabled/{{ domain }}.conf
    notify:
      - restart apache2

  - name: a2dissite default
    command: a2dissite 000-default
    args:
      creates: /etc/apache2/sites-disabled/000-default.conf
    notify:
      - restart apache2

  ##
  # FTP server setup.
  #
  - name: FTP | vsftpd daemon package
    action: apt pkg=vsftpd state=present
    tags: ftp

  - name: FTP | Configuration setup
    action: template src=templates/vsftpd.conf dest=/etc/vsftpd.conf
    tags: ftp

  - name: FTP | Configuration setup
    action: template src=templates/vsftpd.chroot_list dest=/etc/vsftpd.chroot_list
    tags: ftp

  - name: FTP | create user
    user:
      name: "{{ db_name }}"
      update_password: on_create
      password: "{{ db_password }}"
      group: www-data

  - name: Set up home dir for ftp user
    file:
      src: "{{ path }}"
      dest: /home/{{ db_name }}/website
      state: link
    notify:
      - restart vsftpd

  - name: vsftpd disable pam_shells line
    lineinfile: dest=/etc/pam.d/vsftpd regexp="^auth   required        pam_shells.so" line="#auth   required        pam_shells.so" state=present
    notify:
      - restart vsftpd

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted

    - name: restart mysql
      service: name=mysql state=restarted

    - name: restart vsftpd
      service: name=vsftpd state=restarted
