---
- name: Install packages
  apt:
    pkg:
      - mysql-server
      - libmysqlclient-dev
    state: present
    update_cache: yes

- name: Ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

- name: Create mysql user
  action: mysql_user user={{ db_user }} password={{ db_password }} priv='*.*:ALL,GRANT' host=localhost state=present

- name: Create a new database
  mysql_db:
    name: "{{ db_name }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    state: present
